name: Auto Update

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Install Presskit
      run: npm install presskit
    
    - name: Build
      run: |
          npx presskit build
          mv ./build ./docs
    
    - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "Add generated static site"

    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Destination branch to push changes
        branch: "gh-pages"
        force: true
